### ISSUE TITLE
wrong version of grub detection on Ubuntu Trusty

### ISSUE THREAD

**Issue by lkthomas** [hercules-team/augeasproviders_grub#13]
puppet-agent[19114]: Found multiple default providers for kernel_parameter: grub, grub2; using grub

grub-install --version
grub-install (GRUB) 2.02~beta2-9ubuntu1.3

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

how come it's using grub1 instead of grub2 ?!

**Comment by raphink** [comment]
Because the grub2 provider is not marked as default for this os.

**Comment by lkthomas** [comment]
any way to enforce grub2 as default?

**Comment by raphink** [comment]
You can always pass a `provider ` attribute to the resource in DSL. A PR against the provider would be welcome, too.

**Comment by lkthomas** [comment]
Any example?

**Comment by raphink** [comment]
`provided => grub2` in the resource declaration.

**Comment by raphink** [comment]
Fixed in #17
