### ISSUE TITLE
EFI support for all oses, not only fedora

### ISSUE THREAD

**Issue by lapfrank** [hercules-team/augeasproviders_grub#27]
Hi,

Small change request. Issue #16 fixed the EFI support issue for Fedora, but not for every other system. Is there any way to fix the grub2.rb file line 151:

`["/boot/grub/grub.cfg", "/boot/grub2/grub.cfg", "/boot/efi/EFI/fedora/grub.cfg"].each {|c|`

to either use the `"operatingsystem" `variable instead of `"fedora"` or add other OSes to the list like RedHat and CentOS?

Thanks,

**Comment by trevor-vaughan** [comment]
@raphink Yeah, PR forthcoming.

**Comment by trevor-vaughan** [comment]
@lapfrank Mind doing a code review on #28 to make sure it solves your issue sufficiently?
