### ISSUE TITLE
Documentation should be more specific about actions taken

### ISSUE THREAD

**Issue by ggeldenhuis** [hercules-team/augeasproviders_grub#33]
It is not 100% clear from the documentation whether the provider also actually runds grub2-mkconfig after setting/changing settings. It could be argued that it is obvious but for the sake of clarity it would be useful if the documentation could specifically say that grub2-mkconfig is run after setting a value. I looked through the code and that is indeed what happens. I am happy to do a tiny PR for the doc update if there is agreement.

**Comment by kenyon** [comment]
Looks like a duplicate of #40.

**Comment by raphink** [comment]
Thanks @kenyon
