### ISSUE TITLE
grub.cfg isn't being properly updated on EFI systems running CentOS 7

### ISSUE THREAD

**Issue by w3ttr3y** [hercules-team/augeasproviders_grub#4]
grub.cfg isn't being properly updated on EFI systems running CentOS 7

It works as expected on servers with a traditional BIOS, but when run on an EFI system, grub active configuration doesn't get updated.

Looking into the issue a bit, line 111 of lib/puppet/provider/kernel_parameter/grub2.rb says:

``` ruby
["/boot/grub/grub.cfg", "/boot/grub2/grub.cfg"].each {|c|
```

The problem is the system does have a /boot/grub2/grub.cfg file, but the file actively being used is /boot/efi/EFI/centos/grub.cfg

I was going to submit a patch, but since centos is in the name, it would have been very distribution specific so taking a step back to create a more generic version probably makes sense.

Why would /boot/grub2/grub.cfg exist if /boot/efi/EFI/centos/grub.cfg is the active configuration?

Honestly, I don't know; making an educated guess is if I were to change to running in legacy bios mode then the /boot/grub2/grub.cfg file probably gets used.  

EFI requires that there is a partition of a limited number of files systems (e.g. fat16/fat32/etc) that has an EFI folder in the root.  To support this, /boot/efi is a different partition then /boot  So when booting in legacy bios mode, my guess is it acts as if there was no efi and reads the configuration file off of the /boot partition.  Since they are separate partitions, you can't hard link etc, so two copies are maintained.

Thus the "best" solution may be to add a line after 117 (mkconfig "-o", cfg), that looks for files /boot/efi/EFI/_/grub.cfg and if so copies cfg (in this case /boot/grub2/grub.cfg) over /boot/efi/EFI/_/grub.cfg

**Comment by raphink** [comment]
I don't think copying this file in this resource type is a proper solution.

How about managing a file resource for your need?

```puppet
file { '/boot/efi/EFI//grub.cfg':
  ensure => file,
  source => '/boot/grub2/grub.cfg',
}
```

**Comment by paulraines68** [comment]
/boot/grub2/grub.cfg does not exist on my CentOS 7 system using EFI.  So running puppet would give me an error on my kernel_parametering complaining no grub.cfg existed.

So I fixed this by simplying adding "/boot/efi/EFI/centos/grub.cfg" to the list grub2.rb

**Comment by raphink** [comment]
OK. Feel free to provide a PR for that.

**Comment by paulraines68** [comment]
I notice though that /etc/grub2-efi.cfg is a symlink to ../boot/efi/EFI/centos/grub.cfg so it would be a more general option to put in the list assuming you don't anticipate any way the code would not work with symlinks by, for example, doing 'rm' on the given file path before writing out a new file?

**Comment by raphink** [comment]
I think symlinks should work imo.

**Comment by paulraines68** [comment]
I note on non-EFI CentOS 7 systems, it is /etc/grub2.cfg that exists and is
a symlink to /boot/grub2/grub.cfg

I have no idea why the grub2 packages for RHEL/CentOS felt it was necessary
to have the link be named grub-efi.cfg on EFI systems.

I see in the new-kernel-pkg script that it does a readlink on both possible
names to find which one to use.

**Comment by cohdjn** [comment]
I'd like to bump this issue.  I just installed on RHEL 7 and I have the same problem.  Only difference is that the active grub.cfg is /boot/efi/EFI/redhat/grub.cfg.

**Comment by Srisrija** [comment]
Hi,

We have the same issue on RHEL-7. But we are assuming its using  /boot/efi/EFI/redhat/grub.cfg but when the server reboots it couldn't find the kernel and disk to load. We have to give manually at grub loader. I assumed its looking the files in /boot/grub2/grub.cfg so created a symbolic link there and tried. But still same issue.

**Comment by raphink** [comment]
That's surprising. 5e2d464c introduced the support for EFI config files. @trevor-vaughan what do you think?

**Comment by trevor-vaughan** [comment]
@raphink Well, the code certainly looks like it should be doing the right thing.

@Srisrija Can you let us know if running `grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg` produces any errors? I haven't seen any issues when running the commands on a clean system so far.

Also, have you modified your grub2 scripts by hand in any way? It's notoriously difficult to auto-test EFI settings.

**Comment by traylenator** [comment]
HI,

We just run into items related to this

So it's true that this module runs

```
grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg
```

if the file  `/boot/efi/EFI/redhat/grub.cfg` exists.

However if you are running booting with 

```
/etc/grub2.cfg -> ../boot/grub2/grub.cfg
```
then this file is not updated.

I had a look through what a kernel upgrade does which calls `/usr/sbin/new-kernel-pkg`.
In this case `grubby` is called to generate both files for UEFI or Bios mode.

So I believe this module should mkconfig for each file that exists and copy the logic
of a kernel upgrade.
