### ISSUE TITLE
Questions about kernel_parameter and grub_user providers

### ISSUE THREAD

**Issue by linuxdan** [hercules-team/augeasproviders_grub#40]
Is is necessary to run `grub2-mkconfig` or does the provider perform this action or its equivalent ?

Also, it would be nice to have all the parameters listed and explained.

**Comment by raphink** [comment]
Not sure about the first question, maybe @trevor-vaughan knows more about that.

As for parameters and their descriptions, you can run `puppet describe <type>` or refer to the forge page at https://forge.puppet.com/herculesteam/augeasproviders_grub/types

**Comment by linuxdan** [comment]
OK, thanks for that pointer.
Found another (bug|undocumented feature) : 

If I set grub_user "ensure" to absent, it leaves the password lines behind.
I am going to try adding "purge => true," and see what happens

**Comment by linuxdan** [comment]
adding "purge => true," cleared the garbage :D

**Comment by linuxdan** [comment]
By trial and error, I found that running `grub2-mkconfig` is unnecessary and I also figured out how to use https://forge.puppet.com/puppetlabs/reboot properly !

I will have to give it a try on #39 and see what I can figure out
