### ISSUE TITLE
grub_menuentry is broken in EL8 and Fedora 30+

### ISSUE THREAD

**Issue by trevor-vaughan** [hercules-team/augeasproviders_grub#49]
EL8 and Fedora 30+ now use the `blscfg` module to load OS configurations from `/boot/loader/entries`. This means that we're going to have to fall back to `grubby` for systems that include this module in their `/etc/grub2.cfg` configuration until some method can be found to process this information without requiring `grubby`.

**Comment by jcpunk** [comment]
Perhaps parsing `grubenv` would help? 

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_monitoring_and_updating_the_kernel/configuring-kernel-command-line-parameters_managing-monitoring-and-updating-the-kernel#what-are-boot-entries_configuring-kernel-command-line-parameters

**Comment by trevor-vaughan** [comment]
@jcpunk I'm actually working on that now. Luckily, the new rewrite of `grubby` is in BASH so I've been able to reverse engineer things.

Unfortunately, it's kind of a hot mess under the hood and we're going to have to support both BLS and old entries to make this thing make any kind of sense.

Also, updating the root disk seems to update it for all BLS entries (it just keeps getting more fun).

**Comment by trevor-vaughan** [comment]
@jcpunk PR is up if you want to take a look

**Comment by jcpunk** [comment]
Excellent :)
